services:
  # Backend Service (FastAPI)
  - type: web
    name: ai-tutor-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m backend.api.main
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: API_HOST
        value: 0.0.0.0
      - key: API_PORT
        value: 10000
      - key: DEBUG
        value: false
    healthCheckPath: /health

  # Frontend Service (React)
  - type: web
    name: ai-tutor-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://ai-tutor-backend.onrender.com 